spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

server:
  port: 9090
  
spring.jpa:
  hibernate.ddl-auto: create-drop

spring.jackson:
  serialization.write-dates-as-timestamps: false 